name: flutter_layouts
description: Useful & production ready flutter layouts. not as examples, but as package. based on real-world apps
version: 0.0.2+1
author: softmarshmallow <woojoo@softmarshmallow.com>
homepage: https://github.com/softmarshmallow/flutter-layouts
repository: https://github.com/softmarshmallow/flutter-layouts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
